### ISSUE TITLE
Publish a draft roadmap and project goals

### ISSUE THREAD

**Issue by harsimranmaan** [kf5i/k3ai#21]
**Is your feature request related to a problem? Please describe.**

It would be nice to get a feel about the goals of this projects as well as add some roadmap items. I think it would be massively valuable for folks like me who work in this domain, are willing to contribute and can consider this for early adoption.

**Describe the solution you'd like**
A one pager would suffice.

**Comment by alfsuse** [comment]
Great idea indeed and started a work on it:
https://github.com/kf5i/k3ai-site/issues/3
https://github.com/kf5i/k3ai-site/issues/4

I'll open today a PR and link you...as soon I'll have a draft I'll tag you so you may share your feedback :)
Thanks for sharing your feedback that's super important for us!

**Comment by alfsuse** [comment]
Hi @harsimranmaan  we released:

- roadmap: https://github.com/orgs/kf5i/projects/2
- goals: https://docs.k3ai.in/what-we-try-solve-a.k.a-our-goals

The roadmap is still a work in progress since we have to add more issue there..but please let us know the feedback you have on this..

**Comment by harsimranmaan** [comment]
Thanks you so much @alfsuse
