### ISSUE TITLE
Inference Servers

### ISSUE THREAD

**Issue by alfsuse** [kf5i/k3ai#3]
We should allow a user to choose if he wants to install the pipelines only or an inference server and if so, if want to install it along with the pipelines or standalone to create an edge inference server.

We should use a tag like --<name of inference server> (i.e.: --triton for NVIDIA triton inference server)

**Comment by harsimranmaan** [comment]
I think --inference-server=bentoml or triton might be a better option instead of having --bentoml,--triton, --tf etc. flags. Thoughts?

**Comment by alfsuse** [comment]
That's a great suggestion, actually could be a special plugin type instead of using --plugin_name we may have a --plugin_inference=bentoml,--triton,etc... this would add more flexibility

**Comment by alfsuse** [comment]
Tensorflow Serving - ResNet is merged in https://github.com/kf5i/k3ai-plugins/pull/3

**Comment by alfsuse** [comment]
Closing because a duplicate of https://github.com/kf5i/k3ai-plugins/issues/6
