### ISSUE TITLE
KF pipelines bv 1.6.0

### ISSUE THREAD

**Issue by mat-ej** [kf5i/k3ai#33]
**Describe the solution you'd like**
IT would be great if k3ai apply kubeflow-pipelines deployed latest version of KF pipelines kf 1.6.0

**Describe alternatives you've considered**
Currently the version deployed is 1.5.0 which is missing some minor KF features.

**Comment by Gsantomaggio** [comment]
closed via https://github.com/kf5i/k3ai-plugins/commit/0a40092e3103052238d0da5790b79a50a55066b9
